apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::081935045128:role/UdacityFlaskDeployCBKubectlRole
      username: build
     - groups:
       - system:bootstrappers
       - system:nodes
       rolearn: arn:aws:iam::081935045128:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-LAQCJTK9Z1DS
       username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-06-12T02:39:11Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "4193"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: ddb73838-8cd8-4b84-91c9-a663563baf74
